services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 443:443
    container_name: nginx
    volumes:
      - wp_volume:/var/www/html/wordpress
    init: true
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./wordpress
    restart: always
    container_name: wordpress
    volumes:
      - wp_volume:/var/www/html/wordpress
    init: true
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_NAME: ${MARIADB_NAME}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    restart: always
    container_name: mariadb
    volumes:
      - mysql_volume:/var/lib/mysql
    init: true
    env_file:
      - ./.env
    networks:
      - app_network
    healthcheck:
      # wait build then setup wordpress
      test: ["CMD-SHELL", "mysqladmin ping --silent"]

volumes:
  mysql_volume:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/mysql"
      o: bind
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/wp"
      o: bind

networks:
  app_network:
    driver: bridge
