version: '3'
services:
  main:
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
      - 80:80
    container_name: main
    # privileged: true
    # tmpfs:
    #   - /tmp
    #   - /run
