version: '3'
services:
  nginx:
    stdin_open: true
    tty: true
    build:
      context: ./nginx
    ports:
      - 443:443
    container_name: nginx
    volumes:
      - wp_volume:/var/www/html/wordpress
    init: true
    env_file:
      - ./.env
    networks:
      - app_network

  wordpress:
    stdin_open: true
    tty: true
    build:
      context: ./wordpress
    container_name: wordpress
    volumes:
      - wp_volume:/var/www/html/wordpress
    init: true
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - mariadb

  mariadb:
    stdin_open: true
    tty: true
    build:
      context: ./mariadb
    container_name: mariadb
    volumes:
      - mysql_volume:/var/lib/mysql
    init: true
    env_file:
      - ./.env
    networks:
      - app_network
    healthcheck:
      # wait build then setup wordpress
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 1s

volumes:
  mysql_volume:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/mysql"
      o: bind
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/wp"
      o: bind

networks:
  app_network:
    driver: bridge
